services:
  app:
    image: pinkynrg/lazy-cook:latest
    container_name: lazy-cook
    restart: unless-stopped
    ports:
      - "8765:3000"
    volumes:
      - /mnt/data/lazy-cook:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
